<script type="text/javascript">
window.addEventListener('load', () => {
	console.log('\n%cDonglei\'s Homepage%cv3.0.0%c\n', 'padding: 8px; background: #3f5973; font-weight: bold; font-size: large; color: white;', 'padding: 8px; background: #649ab6; font-size: large; color: #eee;','');
	console.log(`The time it takes to load the pages is ${Math.round(performance.now() * 100) / 100}ms`);
});
</script>